import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import {sassPlugin} from "esbuild-sass-plugin";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const mode = process.argv[2] ?? 'watch';
const prod = mode === 'production';

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts',"src/styles.scss"],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    'node:os',
    'node:process',
    ...builtins,
  ],
  format: 'cjs',
  target: 'es2018',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outdir: '.',
  minify: prod,
  plugins: [sassPlugin()],
  drop: prod ? ['console','debugger'] : [],
});

if (mode !== 'watch') {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
